spring:
   datasource:
      username: pet_store
      password: pet_store
      URL: jdbc:mysql://localhost:3306/pet_store
       
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true 
      #defer-datasource-initalization: true
      
   #sql:
      #init:
         #mode: never
      